### ISSUE TITLE
Datasets transformation

### ISSUE THREAD

**Issue by SqLiu67** [IbrahimYang/Hybrid-neural-networks#6]
In the HSN model code，which DVS simulator was used to generate CLEVER-DAVIS and NFS-DAVIS ,or was the datasets taken with an event camera? could U please share the processed DAVIS datasets？Thanks.

**Comment by Developer-KS** [comment]
We have been using a simple script to generate the DVS datasets from CLEVER, NFS, and other APS tracking datasets. The script is basically calculating the temporal difference of the log amplitude of two adjacent APS frames and passing through a threshold function.

**Comment by SqLiu67** [comment]
could U please share the code of the script? Or is the currently published code only valid for "dvsave-2020 _ 07 _ 23 _ 10 _ 28 _ 47. aedat4" and "dvsave-2020 _ 07 _ 23 _ 10 _ 28 _ 03. aedat4"?If I want to use other datasets for input, do I need to modify the code for more details? For example, the threshold when the target is detected before target tracking, etc.Thanks for your answer.

**Comment by Developer-KS** [comment]
The code only works on this toy dataset for now. You will need to write new data loaders for other datasets. Besides, we have been using pre-trained APS feature extractors for large datasets, instead of training both APS and DVS feature extractor networks from scratch like in this demo. That version is not available yet.
